'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdvancedPhonic
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property x As String
    Public Property ck As String
    Public Property ce As String
    Public Property ea As String
    Public Property oa As String
    Public Property ai As String
    Public Property oi As String
    Public Property ay As String
    Public Property ou As String
    Public Property ey As String
    Public Property au As String
    Public Property ew As String
    Public Property igh As String
    Public Property ui As String
    Public Property eigh As String
    Public Property var_vdg As Nullable(Of Integer)

    Public Overridable Property VowelDigraph As VowelDigraph
    Public Overridable Property CodeKnowledge_Summations As CodeKnowledge_Summations

End Class
