'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Assessment
    Public Property AssessmentID As Integer
    Public Property StudentId As Nullable(Of Integer)
    Public Property Group As String
    Public Property [Function] As String
    Public Property Test_Name As String
    Public Property [Date] As Nullable(Of Date)
    Public Property Raw_Score As Nullable(Of Integer)
    Public Property Standard_Score As Nullable(Of Integer)
    Public Property Total_Items As Nullable(Of Integer)
    Public Property OperatorID As String

End Class
