'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BeginningPhonic
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property a As String
    Public Property e As String
    Public Property i As String
    Public Property o As String
    Public Property u As String
    Public Property b As String
    Public Property c As String
    Public Property d As String
    Public Property f As String
    Public Property g As String
    Public Property h As String
    Public Property j As String
    Public Property k As String
    Public Property l As String
    Public Property m As String
    Public Property n As String
    Public Property p As String
    Public Property r As String
    Public Property s As String
    Public Property t As String
    Public Property v As String
    Public Property w As String
    Public Property y As String
    Public Property z As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property ConsonantDigraph As ConsonantDigraph

End Class
