'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Blending_3snd_Words
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property pig As String
    Public Property bug As String
    Public Property hat As String
    Public Property pin As String
    Public Property rat As String
    Public Property bird As String
    Public Property shell As String
    Public Property five As String
    Public Property boat As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Blending_2snd_Words As Blending_2snd_Words
    Public Overridable Property Blending_4snd_Words As Blending_4snd_Words

End Class
