'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Blending_5snd_Words
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property print As String
    Public Property crunch As String
    Public Property plant As String
    Public Property stamp As String
    Public Property street As String
    Public Property blast As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Blending_4snd_Words As Blending_4snd_Words
    Public Overridable Property Blending_Summation As Blending_Summation

End Class
