'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Blending_4snd_Words
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property frog As String
    Public Property grass As String
    Public Property stick As String
    Public Property jump As String
    Public Property under As String
    Public Property mist As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Blending_3snd_Words As Blending_3snd_Words
    Public Overridable Property Blending_5snd_Words As Blending_5snd_Words

End Class
