'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Blending_2snd_Words
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property at As String
    Public Property shee As String
    Public Property may As String
    Public Property saw As String
    Public Property it As String
    Public Property fur As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Blending_3snd_Words As Blending_3snd_Words

End Class
