'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Blending_Summation
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property Two_Sound As Nullable(Of Integer)
    Public Property Three_Sound As Nullable(Of Integer)
    Public Property Four_Sound As Nullable(Of Integer)
    Public Property Five_Sound As Nullable(Of Integer)
    Public Property ClinicianName As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Blending_5snd_Words As Blending_5snd_Words

End Class
