'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CBMData
    Public Property CBMID As Integer
    Public Property StudentId As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property Correct_Words_Each_Minute As Nullable(Of Integer)
    Public Property Errors As Nullable(Of Integer)
    Public Property Timed As Nullable(Of Date)
    Public Property Word_Count As Nullable(Of Integer)
    Public Property Test_Method As String
    Public Property Text_Source As String
    Public Property Reading_Level As String
    Public Property Passage As String

End Class
