'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clinician
    Public Property ClinicianId As String
    Public Property LastName As String
    Public Property FirstName As String
    Public Property Phone As String
    Public Property Cellular As String
    Public Property Alt_Phone As String
    Public Property Email As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property Inactive As Boolean
    Public Property AutoSelect As Nullable(Of Boolean)
    Public Property ClinicianOrder As Integer

End Class
