'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CodeKnowledge_Summations
    Public Property Count As Integer
    Public Property StudentNo As Integer
    Public Property [Date] As Nullable(Of Date)
    Public Property Beginning_Phonics As Nullable(Of Integer)
    Public Property Consonant_Digraphs As Nullable(Of Integer)
    Public Property Vowel_Digraphs As Nullable(Of Integer)
    Public Property Basic_Phonics As Nullable(Of Integer)
    Public Property Advanced_Phonics As Nullable(Of Integer)
    Public Property oneltr_con As Nullable(Of Integer)
    Public Property sv As Nullable(Of Integer)
    Public Property con As Nullable(Of Integer)
    Public Property cdg As Nullable(Of Integer)
    Public Property ovdg As Nullable(Of Integer)
    Public Property var_vdg As Nullable(Of Integer)
    Public Property ClinicianName As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property AdvancedPhonic As AdvancedPhonic

End Class
