'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConsonantDigraph
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property sh As String
    Public Property ch As String
    Public Property th As String
    Public Property qu As String

    Public Overridable Property BeginningPhonic As BeginningPhonic
    Public Overridable Property VowelDigraph As VowelDigraph

End Class
