'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DefaultScheduleFileLocation
    Public Property Index As Integer
    Public Property Student_Schedule_Location As String
    Public Property Office_Schedule_Location As String
    Public Property StorageDate As Nullable(Of Date)

End Class
