'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FamilyLiteracyEntityDataModel
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FamilyLiteracyEntityDataModel")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AdvancedPhonics() As DbSet(Of AdvancedPhonic)
    Public Overridable Property Assessments() As DbSet(Of Assessment)
    Public Overridable Property BeginningPhonics() As DbSet(Of BeginningPhonic)
    Public Overridable Property Blending_2snd_Words() As DbSet(Of Blending_2snd_Words)
    Public Overridable Property Blending_3snd_Words() As DbSet(Of Blending_3snd_Words)
    Public Overridable Property Blending_4snd_Words() As DbSet(Of Blending_4snd_Words)
    Public Overridable Property Blending_5snd_Words() As DbSet(Of Blending_5snd_Words)
    Public Overridable Property Blending_Summation() As DbSet(Of Blending_Summation)
    Public Overridable Property CBMDatas() As DbSet(Of CBMData)
    Public Overridable Property Classrooms() As DbSet(Of Classroom)
    Public Overridable Property Clinicians() As DbSet(Of Clinician)
    Public Overridable Property Clinician_DailyOutSchedule() As DbSet(Of Clinician_DailyOutSchedule)
    Public Overridable Property CodeKnowledge_Summations() As DbSet(Of CodeKnowledge_Summations)
    Public Overridable Property ConsonantDigraphs() As DbSet(Of ConsonantDigraph)
    Public Overridable Property DefaultScheduleFileLocations() As DbSet(Of DefaultScheduleFileLocation)
    Public Overridable Property GridViewColumnSizeAdjustments() As DbSet(Of GridViewColumnSizeAdjustment)
    Public Overridable Property GuardianProfiles() As DbSet(Of GuardianProfile)
    Public Overridable Property Languages() As DbSet(Of Language)
    Public Overridable Property Language_Tests() As DbSet(Of Language_Tests)
    Public Overridable Property Lists() As DbSet(Of List)
    Public Overridable Property MainSchedules() As DbSet(Of MainSchedule)
    Public Overridable Property Memories() As DbSet(Of Memory)
    Public Overridable Property Memory_Tests() As DbSet(Of Memory_Tests)
    Public Overridable Property Phonological_Awareness() As DbSet(Of Phonological_Awareness)
    Public Overridable Property Phonological_Awareness_Tests() As DbSet(Of Phonological_Awareness_Tests)
    Public Overridable Property Rapid_Naming() As DbSet(Of Rapid_Naming)
    Public Overridable Property Rapid_Naming_Tests() As DbSet(Of Rapid_Naming_Tests)
    Public Overridable Property ReadingSources() As DbSet(Of ReadingSource)
    Public Overridable Property Segment_2snd_NonWords() As DbSet(Of Segment_2snd_NonWords)
    Public Overridable Property Segment_2snd_Words() As DbSet(Of Segment_2snd_Words)
    Public Overridable Property Segment_3snd_NonWords() As DbSet(Of Segment_3snd_NonWords)
    Public Overridable Property Segment_3snd_Words() As DbSet(Of Segment_3snd_Words)
    Public Overridable Property Segment_4snd_NonWords() As DbSet(Of Segment_4snd_NonWords)
    Public Overridable Property Segment_4snd_Words() As DbSet(Of Segment_4snd_Words)
    Public Overridable Property Segment_5snd_Words() As DbSet(Of Segment_5snd_Words)
    Public Overridable Property Segmenting_Summation() As DbSet(Of Segmenting_Summation)
    Public Overridable Property Spellings() As DbSet(Of Spelling)
    Public Overridable Property Spelling_Tests() As DbSet(Of Spelling_Tests)
    Public Overridable Property StandardScore_ReferenceTable() As DbSet(Of StandardScore_ReferenceTable)
    Public Overridable Property Stud_Guard_Rel() As DbSet(Of Stud_Guard_Rel)
    Public Overridable Property StudentCurrentReadingLevels() As DbSet(Of StudentCurrentReadingLevel)
    Public Overridable Property StudentHours() As DbSet(Of StudentHour)
    Public Overridable Property StudentInfoes() As DbSet(Of StudentInfo)
    Public Overridable Property StudentNotes() As DbSet(Of StudentNote)
    Public Overridable Property StudentProfiles() As DbSet(Of StudentProfile)
    Public Overridable Property StudentSchools() As DbSet(Of StudentSchool)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Texts() As DbSet(Of Text)
    Public Overridable Property Text_Reading() As DbSet(Of Text_Reading)
    Public Overridable Property Text_Reading_Tests() As DbSet(Of Text_Reading_Tests)
    Public Overridable Property VowelDigraphs() As DbSet(Of VowelDigraph)
    Public Overridable Property Word_Reading() As DbSet(Of Word_Reading)
    Public Overridable Property Word_Reading_Tests() As DbSet(Of Word_Reading_Tests)

End Class
