'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GuardianProfile
    Public Property GuardianID As Integer
    Public Property Last_Name As String
    Public Property First_Name As String
    Public Property Guardian_Type As String
    Public Property Email As String
    Public Property Alt_Email As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property Zip_Code As String
    Public Property Home_Phone As String
    Public Property Cell_Phone As String
    Public Property Work_Phone As String
    Public Property Fax As String

End Class
