'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class List
    Public Property Source_Level As String
    Public Property Source As String
    Public Property Minimum_Form_Level As String
    Public Property Maximum_Form_Level As String
    Public Property Index As Nullable(Of Integer)

    Public Overridable Property ReadingSource As ReadingSource

End Class
