'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MainSchedule
    Public Property key As Integer
    Public Property Count As Nullable(Of Integer)
    Public Property Studentid As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property TimeIn As Nullable(Of Date)
    Public Property Timeout As Nullable(Of Date)
    Public Property Clinicianid As String
    Public Property ClinicianSignature As String
    Public Property Status As String
    Public Property RequestedDate As Nullable(Of Date)
    Public Property RequestedFashion As String
    Public Property Processingclinician As String
    Public Property Attendance As String

End Class
