'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rapid_Naming_Tests
    Public Property index As Integer
    Public Property [Function] As String
    Public Property Test_Name As String
    Public Property Bottom_Standard_Score As Nullable(Of Integer)
    Public Property Top_Standard_Score As Nullable(Of Integer)

End Class
