'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Segment_2snd_NonWords
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property ees As String
    Public Property ta As String
    Public Property koe As String
    Public Property ip As String
    Public Property ak As String
    Public Property aen As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Segment_5snd_Words As Segment_5snd_Words
    Public Overridable Property Segment_3snd_NonWords As Segment_3snd_NonWords

End Class
