'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Segment_4snd_Words
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property frog As String
    Public Property black As String
    Public Property nest As String
    Public Property trip As String
    Public Property hand As String
    Public Property drum As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Segment_3snd_Words As Segment_3snd_Words
    Public Overridable Property Segment_5snd_Words As Segment_5snd_Words

End Class
