'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Segment_3snd_NonWords
    Public Property Count As Integer
    Public Property StudentNo As Integer
    Public Property [date] As Nullable(Of Date)
    Public Property pim As String
    Public Property mif As String
    Public Property sep As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Segment_2snd_NonWords As Segment_2snd_NonWords
    Public Overridable Property Segment_4snd_NonWords As Segment_4snd_NonWords

End Class
