'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Segment_5snd_Words
    Public Property Count As Integer
    Public Property StudentNo As Integer
    Public Property [Date] As Nullable(Of Date)
    Public Property clasp As String
    Public Property stand As String
    Public Property thunder As String
    Public Property ground As String
    Public Property blest As String
    Public Property strive As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Segment_2snd_NonWords As Segment_2snd_NonWords
    Public Overridable Property Segment_4snd_Words As Segment_4snd_Words

End Class
