'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Segment_4snd_NonWords
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property flob As String
    Public Property prif As String
    Public Property sept As String
    Public Property Sum As Nullable(Of Integer)

    Public Overridable Property Segment_3snd_NonWords As Segment_3snd_NonWords
    Public Overridable Property Segmenting_Summation As Segmenting_Summation

End Class
