'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentSchool
    Public Property Count As Integer
    Public Property StudentId As Nullable(Of Integer)
    Public Property SchoolDist As String
    Public Property SchoolName As String
    Public Property Prv_Pub As Boolean

End Class
