'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentInfo
    Public Property ID As Integer
    Public Property Campus As String
    Public Property InitialDate As String
    Public Property FinalDate As String
    Public Property Zip_Code As String
    Public Property Student As String
    Public Property Parent_First_Name As String
    Public Property Parent_Last_Name As String
    Public Property Phone_1 As String
    Public Property Phone_2 As String
    Public Property Phone_3 As String
    Public Property Email_ As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String

End Class
