'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentProfile
    Public Property StudentID As Integer
    Public Property First_Name As String
    Public Property Last_Name As String
    Public Property DOB As Nullable(Of Date)
    Public Property Gender As String
    Public Property District_Zone As String
    Public Property School_Attending As String
    Public Property Initial_Inquiry_Date As Nullable(Of Date)
    Public Property Assessment_Date As Nullable(Of Date)
    Public Property Report_Discussion_Date As Nullable(Of Date)
    Public Property Tutoring_Start_Date As Nullable(Of Date)
    Public Property Tutoring_Stop_Date As Nullable(Of Date)
    Public Property Active As Boolean
    Public Property InitialNotes As String

End Class
