'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VowelDigraph
    Public Property Count As Integer
    Public Property StudentNo As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property ie As String
    Public Property oo As String
    Public Property ue As String
    Public Property ow As String
    Public Property oy As String
    Public Property ee As String
    Public Property aw As String

    Public Overridable Property AdvancedPhonic As AdvancedPhonic
    Public Overridable Property ConsonantDigraph As ConsonantDigraph

End Class
